### ISSUE TITLE
Node-collector hangs on deleted node

### ISSUE THREAD

**Issue by Pionerd** [aquasecurity/trivy-operator#1660]
**What steps did you take and what happened:**

Node-collector job creates a pod with a selector that specifies a specific node. This node gets deleted (in this case because it was a spot instance, but I can imagine cluster autoscaling would trigger similar behaviour). Pods stays pending forever, no new jobs are started. Job needs to be removed manually.

**What did you expect to happen:**
Job either times out and gets removed or recognizes that the node no longer exists. 

**Anything else you would like to add:**

N/A

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.16.4
- Kubernetes version (use `kubectl version`): v1.27.3
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): AKS

**Comment by chen-keinan** [comment]
@Pionerd issue should be fixed with trivy-operator v0.17.0-rc , an official release will be out today

**Comment by BenjaminHerbert** [comment]
@chen-keinan: I have just upgraded to v0.17.1 and can not confirm the full resolution of the problem.

The unschedulable Pod was still there and I could only resolve it by deleting the corresponding Job manually.

**Comment by LMantovan** [comment]
I can confirm what @BenjaminHerbert said. The problem is still here after updating to v0.17.1

**Comment by chen-keinan** [comment]
Thanks for the update, checking

**Comment by LMantovan** [comment]
> Thanks for the update, checking
> 
> qq:
> 
> * this is only happen with `node-collector` , no issues with `scan-job` pod  ?
No issues with scan, I can see all vulnerabilityReports and trivy scans regularly. It happens only with node-collector

> * what is the `status` of the hanging pod ?
My status is `0/4 nodes are available: 1 node(s) had untolerated taint {workspace-taint: }, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling..`

**Comment by chen-keinan** [comment]
> 
> > * what is the `status` of the hanging pod ?
> >   My status is `0/4 nodes are available: 1 node(s) had untolerated taint {workspace-taint: }, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling..`

you are using tolerations ?

**Comment by LMantovan** [comment]
I'm sorry, yes i'm using tolerations in the cluster

**Comment by KateFiroozi** [comment]
I  am using trivy-operator-0.18.4  on AKS and I have the same issue.
I have added tolerations to the helm chart values file for default nodes, but batch is still "hanging" on nodes not present in the cluster anymore.
Any workaround how to get rid of them?

**Comment by chen-keinan** [comment]
@LMantovan @KateFiroozi thank you for clarifications , I'll have a look at it again next week.
currently the only workaround I can offer is to disable infraAssessment report by setting this [flag](https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml#L81).

**Comment by KateFiroozi** [comment]
clarification, I have made a mistake of adding toleration "the wrong place" in a chart. The correct one was trivyOperator.scanJobTolerations. I still had to do hard refresh with argocd on my trivy-operator instance and had to manuelly delete a job object.
