### ISSUE TITLE
Got error "unable to run trivy operator: starting controllers manager"

### ISSUE THREAD

**Issue by GregoryLazarev** [aquasecurity/trivy-operator#654]
**What steps did you take and what happened:**

I deployed trivy-operator via Helm. After deploy it works for some time, then crashes. Last message in operator logs is 

`unable to run trivy operator: starting controllers manager: [failed to wait for ingress caches to sync: timed out waiting for cache to be synced, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded]
`

Operator fails with this error when just part of cluster is scanned and new scan jobs not starts after operator restart. 

**What did you expect to happen:**

Operator should work stable, without crashes.

**Anything else you would like to add:**

I used next values:
```
operator:
  scanJobTimeout: 30m
  scanJobsRetryDelay: 1m
  scannerReportTTL: 48h
trivy:
  additionalVulnerabilityReportFields: Description, Links, Target, Class
  githubToken: GH_token
  ignoreUnfixed: true
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 750m
      memory: 500Mi
  timeout: 15m0s
```

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): 0.5.0
- Kubernetes version (use `kubectl version`): 1.18.6
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): macOS 13

**Comment by chen-keinan** [comment]
@GregoryLazarev is this happen every time the operator is running  ?

**Comment by GregoryLazarev** [comment]
@chen-keinan Yes, every time

**Comment by chen-keinan** [comment]
> @chen-keinan Yes, every time

thanks this input , just to clarify, you get this error `failed to wait for ingress caches to sync: timed out waiting for cache to be synced` every time ?

**Comment by GregoryLazarev** [comment]
Exactly 😞 Same error every time. Even after restart

**Comment by chen-keinan** [comment]
@GregoryLazarev  I have released `trivy-operator v0.6.0-rc3`  please confirm it solve your issue

**Comment by GregoryLazarev** [comment]
Unfortunately, problem still exists. Same error appears in nearly 1-2 hours operator working

**Comment by chen-keinan** [comment]
> Unfortunately, problem still exists. Same error appears in nearly 1-2 hours operator working

thanks for update, can you please check how many resources of ingress do you have in your cluster ?

**Comment by GregoryLazarev** [comment]
I've installed with `configAuditScannerEnabled=false` and for 8 hours there are no errors like `failed to wait for ingress caches to sync`. I'll check again tomorrow, but now it looks like everything works

**Comment by chen-keinan** [comment]
ok , thanks for update , I have added small change in `trivy-operator v0.6.0` , that might help to fix the problem. you can install it as usual , without additional setting. (no need to set this flag `configAuditScannerEnabled=false`) let me know afterwards if it works for you.

**Comment by GregoryLazarev** [comment]
Checked in 0.6.0-rc3 with `configAuditScannerEnabled=false`. Error appears again. Now 
![image](https://user-images.githubusercontent.com/39768466/201859435-6a1423a6-40ca-482e-bf1f-2e0a376d08d9.png)

**Comment by chen-keinan** [comment]
@GregoryLazarev just to confirm above you mention :

>I've installed with configAuditScannerEnabled=false and for 8 hours there are no errors like failed to wait for ingress caches to sync. I'll check again tomorrow, but now it looks like everything works

you tested it again when the `configAuditScannerEnabled=false` is set and error appear again ? is this appear after 8 hours ?

**Comment by GregoryLazarev** [comment]
I can't say for sure if the error appeared after 8 hours or earlier. But this time the operator definitely worked longer before crush with this error.

**Comment by chen-keinan** [comment]
thanks for confirmation.
Another info question , how many `ingress` resources you have in your cluster? are all of them in use ?

**Comment by GregoryLazarev** [comment]
We have 447 ingress resources. Some of them are old and will be deleted soon, but most of ingresses are in use. 


I installed v0.6.0 and now operator works without crashes for more than 20 hours. Loos like this problem is solved, thanks alot. 
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/39768466/202093075-386a87b1-45bb-4ce5-a02e-cc4cc4f9f5ff.png">

**Comment by chen-keinan** [comment]
> We have 447 ingress resources. Some of them are old and will be deleted soon, but most of ingresses are in use.
> 
> I installed v0.6.0 and now operator works without crashes for more than 20 hours. Loos like this problem is solved, thanks 

Thanks,  keep me updated if something changes

**Comment by chen-keinan** [comment]
@GregoryLazarev can we close this issue ?
